### ISSUE TITLE
Use encrypted secrets forGitHub Actions

### ISSUE THREAD

**Issue by hschilling** [nasa-petal/petal-labeler-data-pipeline#9]
For maintaining API keys and such, consider using

https://docs.github.com/en/actions/security-guides/encrypted-secrets

GitHub Actions can inject your secrets into the environment as environment variables: https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow

**Comment by dsmith111** [comment]
Completed by @bruffridge
